# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Get top10 data

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0,6,12,18 * * *"

jobs:
  runscript:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.14
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.14

      - name: Config git
        run: |
          git config user.email "ww-rm@qq.com"
          git config user.name "ww-rm"
          git pull --ff

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r "requirements.txt"

      - name: Run Script
        run: |
          python3 "main.py"

      - name: Commit gentop10
        run: |
          git add .
          bash "safe_commit.sh" "autorun-getdata"
          git pull --ff
          git push
